name=str(input("name:"))
math=int(input("math:"))
science=int(input("science:"))
art=int(input("art:"))
PE=int(input("PE:"))
literature=int(input("literatura:"))
scores=[math,science,art,PE,literature]
scores.sort()
print("-------------")
max=scores[4]
a=abs(max-20)
math=math+a
science=science+a
art=art+a
PE=PE+a
literature=literature+a
#print(f"math:{math},science:{science},art:{art},PE:{PE},literature:{literature}")
print("math:",math)
print("science:",science)
print("art:",art)
print("PE:",PE)
print("literature:",literature)
scores=[math,science,art,PE,literature]
print(scores)